FORMAT: 1A
HOST: http://localhost/

# doomaster API 1.0.6 (2018-01-22 10:40)

Testovací verze pro DM v 1.0.

## Konkrétní Device [/select/devices/{id}]

Vrátí nebo změní konkrétní zařízení, s pořadovým číslem uvedeným v URL. Pořadové číslo může být jiné než ID zařízení.

### Stav zařízeni [GET]

GET: vrátí všechny položky konkrétního zařízení.

Např. zařízení s pořadovým číslem 1 má URL 
http://localhost:1818/select/devices/1



+ Parameters
    + id (number) - konkretni ID device (integer)

+ Response 200 (application/json)

        
             {
                "devSerTime" : "2018-01-14 18:25:21",
                "devId": 12345678900,
                "devType": "kamera",
                "devTime": "2018-01-14 18:25:21",
                "devTemp": -9,
                "devLight": 2,
                "devAlarm": false,
                "devWater": 35,
                "devPosition": 35,
                "devCamIP": "http://192.168.0.40/jpg/image.jpg",
                "devName": "bouda 0",
                "devWeatherIP": "http://meteosluzby.e-pocasi.cz/pocasi/56942063d560c.png"
             }
        

    
### Změna stavu [PUT]

PUT: měníme stav, některé položky, zařízení s pořadovým číslem uvedeným v URL. Stačí jen uvést klíč a hodnotu dané položky. 

Např. Změna jména z "bouda 0" na "Kotelna" se provede takto (PUT)http://localhost:1818/select/devices/1

+ Parameters
    + id (number) - konkretni pořadové číslo device  (integer)
    
+ Request (application/json)

        
             {
                 "devName":"Kotelna"
             }
        

+ Response 201 (application/json)









## Všechny Devices [/select/devices/]

Vrací pole, kde všechny prvky mají stejné položky v této stuktuře 

(jmeno, typ, ukazka dat) 

* devSerTime  string      2018-01-14 18:25:21 //cas na serveru
* devId       int         12345678900 
* devType     string      teplota  //teplota, voda, svetlo, alarm, brana, kamera, pocasi
* devTime     string      2018-01-14 18:25:21    
* devTemp     int         -9      // (-100 - +100)
* devLight    int         2       //0,1,2,3,4 (podle čísla mění barvu
* devAlarm    bool        false   //true je alarm, false není alarm 
* devWater    int         12      // 0 - 100: kolik procent je voda
* devPosition int         31      // 0 - 100: kolik procent je otevrena brána
* devCamIP    string      http://192.168.0.40/jpg/image.jpg       //adresa na obrázek z kamery. 
* devName     string      bouda 11    //název zařízení
* devWeatherIP string      http://meteosluzby.e-pocasi.cz/pocasi/56942063d560c.png       //adresa na obrázek z pocasi. 

### Fordhand je napsaný tak,
že v JSON má libovolný počet dat v libovolném pořadi 





### Všechna zařízení [GET]

GET: vrátí POLE s položkami všech zařízení.

http://localhost:1818/select/devices/

+ Response 200 (application/json)

                [{
                    "devSerTime": "2018-01-22 10:22:47",
                    "devId": 12345678900,
                    "devType": "teplota",
                    "devTime": "10:22:47",
                    "devTemp": 17,
                    "devLight": 4,
                    "devAlarm": false,
                    "devWater": 78,
                    "devPosition": 78,
                    "devCamIP": "http://192.168.0.19/jpg/image.jpg",
                    "devName": "bouda 0",
                    "devWeatherIP": "http://meteosluzby.e-pocasi.cz/pocasi/56942063d560c.png"
                }, {
                    "devSerTime": "2018-01-22 10:22:47",
                    "devId": 12345678901,
                    "devType": "pocasi",
                    "devTime": "10:22:47",
                    "devTemp": 18,
                    "devLight": 4,
                    "devAlarm": false,
                    "devWater": 78,
                    "devPosition": 78,
                    "devCamIP": "http://192.168.0.26/jpg/image.jpg",
                    "devName": "bouda 1",
                    "devWeatherIP": "http://meteosluzby.e-pocasi.cz/pocasi/56942063d560c.png"
                }, {
                    "devSerTime": "2018-01-22 10:22:47",
                    "devId": 12345678902,
                    "devType": "brana",
                    "devTime": "10:22:47",
                    "devTemp": 19,
                    "devLight": 4,
                    "devAlarm": false,
                    "devWater": 78,
                    "devPosition": 78,
                    "devCamIP": "http://192.168.0.26/jpg/image.jpg",
                    "devName": "bouda 2",
                    "devWeatherIP": "http://meteosluzby.e-pocasi.cz/pocasi/56942063d560c.png"
                }, {
                    "devSerTime": "2018-01-22 10:22:47",
                    "devId": 12345678903,
                    "devType": "voda",
                    "devTime": "10:22:47",
                    "devTemp": 20,
                    "devLight": 4,
                    "devAlarm": false,
                    "devWater": 78,
                    "devPosition": 78,
                    "devCamIP": "http://192.168.0.26/jpg/image.jpg",
                    "devName": "bouda 3",
                    "devWeatherIP": "http://meteosluzby.e-pocasi.cz/pocasi/56942063d560c.png"
                }, {
                    "devSerTime": "2018-01-22 10:22:47",
                    "devId": 12345678904,
                    "devType": "alarm",
                    "devTime": "10:22:47",
                    "devTemp": 21,
                    "devLight": 4,
                    "devAlarm": false,
                    "devWater": 78,
                    "devPosition": 78,
                    "devCamIP": "http://192.168.0.26/jpg/image.jpg",
                    "devName": "bouda 4",
                    "devWeatherIP": "http://meteosluzby.e-pocasi.cz/pocasi/56942063d560c.png"
                }, {
                    "devSerTime": "2018-01-22 10:22:47",
                    "devId": 12345678905,
                    "devType": "teplota",
                    "devTime": "10:22:47",
                    "devTemp": 22,
                    "devLight": 4,
                    "devAlarm": false,
                    "devWater": 78,
                    "devPosition": 78,
                    "devCamIP": "http://192.168.0.26/jpg/image.jpg",
                    "devName": "bouda 5",
                    "devWeatherIP": "http://meteosluzby.e-pocasi.cz/pocasi/56942063d560c.png"
                }, {
                    "devSerTime": "2018-01-22 10:22:47",
                    "devId": 12345678906,
                    "devType": "kamera",
                    "devTime": "10:22:47",
                    "devTemp": 23,
                    "devLight": 4,
                    "devAlarm": false,
                    "devWater": 78,
                    "devPosition": 78,
                    "devCamIP": "http://192.168.0.26/jpg/image.jpg",
                    "devName": "bouda 6",
                    "devWeatherIP": "http://meteosluzby.e-pocasi.cz/pocasi/56942063d560c.png"
                }]